---
- name: Instalar paquetes y actualizar
  hosts: Server_ProxyInversoInstall
  become: yes

  vars_files:
    - paquetes/install_paquetes.yml
    - vars/datos_generales.yml

  tasks:
#    - name: Incluir tareas de modificación de sources.list                       ## Tareas OK
#      include_tasks: tareas/tasks_sources.list.yml

    - name: Incluir tareas para actualizar y upgradear de paquetes
      include_tasks: tareas/tasks_update-upgrade.yml

#    - name: Incluir tareas de instalación de Nginx
#      include_tasks: tareas/tasks_install_nginx.yml